/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myapp;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import util.ConnectionFactory;

public class App {
//    public String getGreeting() {
//        return "Hello World!";
//    }
//
    public static void main(String[] args) {
        
        

         String sql = "INSERT INTO tasks (idProject, name, description,"
                + "isCompleted, notes) VALUES (?, ?, ?, ?, ?);";
        
        Connection conn = null;
        PreparedStatement statement = null;
        
        try {
            conn = ConnectionFactory.getConnection();
            statement = conn.prepareStatement(sql);
            statement.setInt(1, 3);
            statement.setString(2, "teste");
            statement.setString(3, "teste");
            statement.setBoolean(4, false);
            statement.setString(5, "teste");
            //statement.setDate(6, new Date());
            //statement.setDate(7, new Date());
            //statement.setDate(8, new Date());
            statement.execute();
            
            
        } catch (Exception e) {
            throw new RuntimeException("Erro ao salvar tarefa " + e.getMessage(), e);
        } finally {
            ConnectionFactory.closeConnection(conn, statement);
        }
    }
}

